---
# tasks file for osm_haproxy

# ensuring haproxy installation on ubuntu
- name: Ensure HAProxy is installed (Debian).
  apt: name=haproxy state=installed
  when: ansible_os_family == 'Debian'

# enabling haproxy in init scripts
- name: Ensure HAProxy is enabled (so init script will start it on Debian).
  lineinfile:
    dest: /etc/default/haproxy
    regexp: "^ENABLED.+$"
    line: "ENABLED=1"
    state: present
  when: ansible_os_family == 'Debian'

# Ensuring haproxy installation on RHEL/centOS
- name: Ensure HAProxy is installed (RedHat).
  yum: name=haproxy state=installed
  when: ansible_os_family == 'RedHat'

# copying haproxy configuration files
- name: Copy HAProxy configuration in place.
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  #  validate: haproxy -f %s -c -q
  notify: restart haproxy

#Enabling haproxy on boot
- name: Ensure HAProxy is started and enabled on boot.
  service: name=haproxy state=started enabled=yes
